### ISSUE TITLE
データベースの内容変更

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texserver#16]
@TakenokoPro 
すいません、なんかそもそもデータベースをコマンドで作成というのがよくわかっていないと思うんです(;´･ω･)
いつもデータベースを作ってからモデルを作ってコントローラーを作っていたから(-_-;)

どこのファイルをいじってコマンドを打ったらデータベースが作成できるんでしょう？
migrationファイル？

あと、やっぱり前回言っていたデータベース構造がよくわからなくて頭が爆発しそう(;'∀')
カテゴリに愛知県が増えたら困るというのは分かったんですけど、
parent_id=NULLなら親がいないってことだから一番上の階層（愛知など）で
parent_id=1（愛知のid）なら南山大学などで、
parent_id=10（南山大学のid）なら外国語学部
ってことだったら、category_idが、そのままparent_idになることになるんでしょうか？

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
錯綜してるね。

順々に回答するね。

> どこのファイルをいじってコマンドを打ったらデータベースが作成できるんでしょう？
> migrationファイル？

これは、
https://github.com/tekuppi1/texserver/blob/develop/config/Migrations/20160922160012_texdata_migration.php
このファイル。
各ローカル環境でマイグレーション出来たのか確認できてないかな？
前のコマンド`cake migrations migrate`で、
ローカルのMySQLに勝手に上のファイルに書いたテーブルが生成できるはず。

新しいマイグレーションファイルを作るときは、
`20160922160012_texdata_migration.php` 
このファイル名を新しい日時に変更してから、`cake migrations migrate`
すると過去にテーブルが作成してあっても、新しいテーブルに更新される。

> parent_id=NULLなら親がいないってことだから一番上の階層（愛知など）で
> parent_id=1（愛知のid）なら南山大学などで、
> parent_id=10（南山大学のid）なら外国語学部ってことだったら、category_idが、そのままparent_idになることになるんでしょうか？

これはその通りで、見た目上はcategory_idの中にparent_idが内包するね。
こうすれば、型が同じテーブルを持つ必要が無くなるから良いんだけど。
今は、深く考えない方が良いかも。

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
あまりにも悲惨なんですけど、まえも言っていたphp.iniの変更が反映されないので、なかなか進まなくて、いろいろインストールし直したりして、とにかく紆余曲折しすぎてます（滝汗）

と、思っていたら、まさに今、その壁を乗り越えた気がする。。。！
ただ、
There was a problem connecting to the database : SQLSTATE[HY000][1045]Access denied for
とかいうエラーが出てきてしまったので、どっかのファイル（database.php?）に自分のデータベースのユーザ名とパスワードを書かないとあかんですよね？

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
20160922160012_texdata_migration.php 
このファイルを新しい日時に書き換えるっていうのは、手動なんですか？(;'∀')
自動で書き換えとかではなく。。？

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
で、データベースって、そのまま
book_datasテーブルに対して、
category_datasテーブルのみで、カラムにcategory_id,parent_id,name
でよいってことですか？

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
一旦、整理しよう(´・ω・`)
今は、起動が出来てマイグレーションが出来ていない状態？

https://github.com/tekuppi1/texserver/blob/develop/config/app.php#L232
データベースにアクセスするには、ユーザーとパスワードをここを書き換えないといけないよ。

で、`20160922160012_texdata_migration.php`
このファイルは、もしもデータベースのテーブルの構造を書き換える場合に使うだけだから、
頻繁に書き換えることは無いはず。

**Comment by TakenokoTech** [comment]
データベースは一旦は今のままにしておこう。
不都合が出たら書き換えよう。

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
マイグレーションできました！
なぜかテーブルが二つしかできなかったけど(;'∀')

**Comment by TakenokoTech** [comment]
出来てないんでねーかな

**Comment by hatimitusiropp** [comment]
やっぱできてないのか。。

**Comment by TakenokoTech** [comment]
テーブルのスクショほしいかな

**Comment by hatimitusiropp** [comment]
![1](https://cloud.githubusercontent.com/assets/12024948/19481258/4764c51a-9588-11e6-9eee-94b603ea2222.png)

**Comment by TakenokoTech** [comment]
![snapcrab_noname_2016-10-18_23-15-13_no-00](https://cloud.githubusercontent.com/assets/9033882/19481390/bb5a120e-9588-11e6-8e33-7bfaf93ef7bf.png)
こうなるはずなんだけどなぁーーー

**Comment by hatimitusiropp** [comment]
![3](https://cloud.githubusercontent.com/assets/12024948/19481593/6295bf6e-9589-11e6-9820-d20be8ff5d2d.png)

**Comment by hatimitusiropp** [comment]
ブランチを変えてやってみたらできた！
書き換えちゃったのが書き換え方がダメだったのかも(;'')

**Comment by TakenokoTech** [comment]
よかった！
いったんは解決？

**Comment by hatimitusiropp** [comment]
解決！

**Comment by TakenokoTech** [comment]
おっけ！！
では、内容変更も今のところなしってことでクローズしますね！
