### ISSUE TITLE
【FW】認証のシステム開発

### ISSUE THREAD

**Issue by TakenokoTech** [tekuppi1/texserver#18]
認証系のロジック開発が未完です。
- [ ] 管理者アカウントをどう作るか。(これはgithub上では話さない方が良いかも)
- [x] 管理者権限は複数必要か？(登録が出来る。閲覧のみ可。システムまで触れるなど)
- [x] 暗号化処理

**Comment by hatimitusiropp** [comment]
管理者権限（２つくらいでいいと思う）
　・閲覧はできるけど、本の編集や、古本市の日付と時間を入力することはできない
　・基本的になんでもできる

暗号化処理
　ここら辺のことがまだよくわかっていないけど、パスワードをどうやって暗号化するのかってことですか？
　http://book.cakephp.org/2.0/ja/core-libraries/components/authentication.html
　↑　このページを参考にして考えてるんですけどよいでしょうか？

**Comment by TakenokoTech** [comment]
@hatimitusiropp  答えまーす！

> 管理者権限（２つくらいでいいと思う）
> 　・閲覧はできるけど、本の編集や、古本市の日付と時間を入力することはできない
> 　・基本的になんでもできる

ふむふむ。
Texchangeメンバー一人ずつに対して一つアカウントを作る必要はないってことでよい？

> 暗号化処理
> 　ここら辺のことがまだよくわかっていないけど、パスワードをどうやって暗号化するのかってことですか？
> 　http://book.cakephp.org/2.0/ja/core-libraries/components/authentication.html
> 　↑　このページを参考にして考えてるんですけどよいでしょうか？

そのページの内容でOKです。
昨日一旦は、アカウント情報管理できるようにしたのでおっけっす。

**Comment by hatimitusiropp** [comment]
> ふむふむ。
> Texchangeメンバー一人ずつに対して一つアカウントを作る必要はないってことでよい？

そうです！運営さん用のアカウントを、幹部レベルとそうじゃない人で分けようか迷ってるくらいです

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
おっけーです。
メーリング機能とか付けるなら一人一人アカウント持ってても良いかなぁとは思ったけど、共有の方が管理しやすいから、そっちにしときましょ。
パスワードを変更したい時が考えものだな(｡-_-｡)

**Comment by TakenokoTech** [comment]
#17 にて対応したので、クローズします！！
