### ISSUE TITLE
本の一覧を表示させるコントローラーについて

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texserver#25]
@TakenokoPro 
今、src/Controller/BooklistControllerで本管理ページに情報を送ろうとしているのかなと思ってるんですけど、
データベースのレコード名がbooksだからBooksControllerじゃないと動かないのかなと思いました。

で、src/Model/Book.phpを作成して、Template/Booksを作ってTemplate/Books/index.ctpから本の情報を取得することができたんですけど、BookllistのViewにも情報を渡すことってできるんでしょうか？

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
とりあえず、追加したissueについての変更をすべてやってしまったブランチをプッシュしてしまいました(;'∀')
コミットで分けてるけど

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
了解っす。
最近、自分立て込んでるんでレビュー返すの遅くなるから
別の作業に手つけててくれると有難き（・ω・）ノ

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
ブランチ名は何ぞ

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
ブランチ名はf_database
になってますが、データベースは一切変更しておりません(;'∀')

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
うっす

**Comment by hatimitusiropp** [comment]
@TakenokoPro 
とりあえず、古本市入力作っておきます

**Comment by TakenokoTech** [comment]
一旦、本の情報を取得する方法は、InitController.php を参考にしてくれればいいかな。
特殊な条件で振り分けたい場合は、後で機能追加していく方針で。

http://localhost/texserver/init.json
↑これ見れるかな
データベースのbooks埋めて確かめてみて！

**Comment by TakenokoTech** [comment]
一旦、#35 で改修させてください。
