### ISSUE TITLE
管理者用ダッシュボードの作成

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texserver#5]
- [ ] ログイン画面  by翠
- [ ] ダッシュボード by木村
- [ ] 出品画面(page)　byめぐみ
- [ ] 確認画面（confirm box）　by翠
- [ ] 古本市予定入力画面(add page)  by木村
- [ ] 確認画面(confirm box)　by翠
- [ ] 古本市予定一覧画面(list update page)　by翠
- [ ] 本の管理画面　byめぐみ

**Comment by TakenokoTech** [comment]
@hatimitusiropp

タスク把握しましたー！
結構タスクが細分化されてるけど、12月リリースと3月リリースがあるんだっけ？
出来れば、分けてissueに上げてラベルとassignを入れてもらえるとありがたい。

**Comment by hatimitusiropp** [comment]
おけです！

**Comment by TakenokoTech** [comment]
レイアウトとかあったらあげて欲しいのぉ

**Comment by hatimitusiropp** [comment]
レイアウトはまだ決まってないので、ちょいまちになりそうです(・・;)
日曜から作り始める予定です

**Comment by TakenokoTech** [comment]
@hatimitusiropp 
了解っす。進展あったら教えてきゅださい(^_-)-☆
一旦、このissue閉じますー。

**Comment by TakenokoTech** [comment]
・ログイン画面 by翠
　↓
・ダッシュボード（左にメニュー　｛出品、予約確認、古本市予定入力、古本市予定確認・更新画面,、本の一覧確認・取引完了｝）　by木村
　↓
・出品画面(page)　byめぐみ
　・ISBN
　・名古屋大学、南山大学、その他（parent）
　・学部,カテゴリ（child）
　↓
・確認画面（confirm box）　by翠
　・本のタイトル（ISBNから取得）
　・画像（ISBNから取得）
　・Yeｓ、No

・古本市予定入力画面(add page) by木村
　・日付(date)
　・開始時刻(starting_time)
　・終了時刻(ending_time)
　・大学名(college)
　・教室名(classroom)
　↓
・確認画面(confirm box)　by翠
　・Yes,No

・古本市予定一覧画面(list update page)　by翠
　すべての古本市の情報を日付が近い順に表示する
　一覧(select)・削除(delete)・更新(update)

・本の管理画面　byめぐみ
　一覧(select)・取引完了(stockを-1)・検索

**Comment by TakenokoTech** [comment]
こんなイメージかな？
http://www.nxworld.net/inspiration/admin-dashboard-design-showcase-1.html

**Comment by hatimitusiropp** [comment]
そうですそうです、こんな感じ('∀')
できたらごちゃごちゃしすぎないシンプルな奴がいいと思ってます

**Comment by TakenokoTech** [comment]
了解です。

想定してる感じになるようにフレーム作ります。
ノディも時間あったらコメント下さい(*´ｰ｀)
