### ISSUE TITLE
【FW】【VIEW】フレームワーク

### ISSUE THREAD

**Issue by TakenokoTech** [tekuppi1/texserver#6]
## 実装内容
- #16 データベースの内容変更
## 欲しいライブラリ
- Underscore.php
  http://brianhaveri.github.io/Underscore.php/
- スマホのブラウザから写真取得 [ File API ]
  HTML5標準機能(ライブラリ使っても良し)
- バーコードリーダー[ https://github.com/EddieLa/JOB ]
  スマホとPCを上手く連動させたい
- 写真のディレクトリに保存[http://app-review.poox.xyz/archives/1289]
  サムネイル用に小さい画像も用意すると良いかも（あくまでDB管理の為に）
## 要望
- ある程度開発終わったら、アクセスログ入れてセキュリティ強化とアクティブユーザーをグラフ化したいね。

**Comment by TakenokoTech** [comment]
## #16 データベースの内容変更

これは、このisuueで片づけちゃいましょう！

**Comment by TakenokoTech** [comment]
カメラでバーコード読み込むやつ、WebRTCでも出来そうなんで調べてみますー。

**Comment by TakenokoTech** [comment]
これ出来そうだけど、商用になりそうなくらい敷居高いので、
自分がパッケージの製造してnpm install 出来るようにしても良いですか？

２ヶ月はかかるかな？

**Comment by hatimitusiropp** [comment]
え！めっちゃすごいっす！！！
それってバーコード読み取り機能ですよね？
ブラウザ間でバーコード取り扱うってことですか？

**Comment by TakenokoTech** [comment]
そういうことー。出来るか分からないけど、出来たらお金取れるレベルやで（笑）

**Comment by TakenokoTech** [comment]
一旦、クローズ
